/**
 * Generated capability host (generator-owned — regenerated by @mdt/generator).
 * Loads every capability module used by the project and wires the project's
 * capability instances (config, secret env names, granted permission scopes).
 * server/index.js consumes this module — it is the security boundary.
 */

import { manifest as cap_datetimeManifest, execute as cap_datetimeExecute } from './datetime.js'
import { manifest as cap_web_fetchManifest, execute as cap_web_fetchExecute } from './web_fetch.js'
import { manifest as cap_web_searchManifest, execute as cap_web_searchExecute } from './web_search.js'

/** capability id → { manifest, execute } for every capability used by the project. */
export const capabilityExecutors = {
  "datetime": { manifest: cap_datetimeManifest, execute: cap_datetimeExecute },
  "web_fetch": { manifest: cap_web_fetchManifest, execute: cap_web_fetchExecute },
  "web_search": { manifest: cap_web_searchManifest, execute: cap_web_searchExecute },
}

/** Project capability instances with resolved config/permission wiring. */
export const capabilityInstances = [
  {
    instanceId: "01990000-7000-7000-8000-040000000001",
    capabilityId: "web_search",
    config: {
  "count": 3,
  "provider": "mock"
},
    secretEnv: {},
    grantedScopes: [
  "network"
],
  },
  {
    instanceId: "01990000-7000-7000-8000-040000000002",
    capabilityId: "web_fetch",
    config: {},
    secretEnv: {},
    grantedScopes: [
  "network"
],
  },
  {
    instanceId: "01990000-7000-7000-8000-040000000003",
    capabilityId: "datetime",
    config: {},
    secretEnv: {},
    grantedScopes: [],
  },
]
