/**
 * Generated variable definitions (generator-owned — regenerated by
 * @mdt/generator). Importing this module registers every variable into its
 * scope store with the documented persistence semantics:
 * project/session → localStorage, page → in-memory.
 */
import { registerVariables, type VariableDefinition } from './variables'

export const generatedVariables: VariableDefinition[] = [
  {
    "defaultValue": "",
    "id": "01990000-7000-7000-8000-060000000001",
    "name": "Last Query",
    "scope": "session",
    "type": "string"
  },
  {
    "defaultValue": "en",
    "id": "01990000-7000-7000-8000-060000000002",
    "name": "Research Locale",
    "scope": "project",
    "type": "string"
  }
]

registerVariables(generatedVariables)
