/**
 * Generated route table (generator-owned — regenerated by @mdt/generator).
 * One route per MDT page of type "page"; the first page is the index route.
 * Modal/drawer/popover pages are overlays rendered by their host page.
 */
import type { ComponentType } from 'react'

import HomePage from './pages/HomePage'
import ResearchPage from './pages/ResearchPage'
import DetailsPage from './pages/DetailsPage'

export interface PageRoute {
  path: string
  pageId: string
  component: ComponentType
}

export const pageRoutes: PageRoute[] = [
  { path: '/', pageId: '01990000-7000-7000-8000-010000000001', component: HomePage },
  { path: '/research', pageId: '01990000-7000-7000-8000-010000000002', component: ResearchPage },
  { path: '/details', pageId: '01990000-7000-7000-8000-010000000003', component: DetailsPage },
]
