/**
 * Generated by @mdt/generator — MDT page 'Details' (01990000-7000-7000-8000-010000000003).
 * Generator-owned: edits may be overwritten on regeneration
 * (see .mdt/generator-manifest.json).
 */
import { MdtButton } from '../elements/MdtButton'
import { generatedVariables } from '../generated-variables'
import { mdtElementStyle } from '../elements/layout'
import { resolveSource } from '../bindings'
import { storeForScope } from '../variables'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function DetailsPage() {
  const navigate = useNavigate()
  const [values, setValues] = useState<Record<string, unknown>>({})
  const [agentOutputs, setAgentOutputs] = useState<Record<string, string>>({})
  const [capabilityOutputs, setCapabilityOutputs] = useState<Record<string, unknown>>({})
  const setValue = (elementId: string, value: unknown): void => {
    setValues((previous) => ({ ...previous, [elementId]: value }))
  }
  const bindingCtx = { values, variables: generatedVariables, agentOutputs, capabilityOutputs }
  async function run_0(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000003 (click)
    navigate(-1)
  }
  return (
    <div className="mdt-page" data-mdt-page='Details' data-mdt-id='01990000-7000-7000-8000-010000000003' style={{ width: 1440, height: 1024 }}>
      <div
        data-mdt-id='01990000-7000-7000-8000-020000000007'
        style={mdtElementStyle({ "height": 60, "width": 640, "x": 40, "y": 40 }, { "font-size": 28 })}
      >
        {'Result details'}
      </div>
      <MdtButton
        mdtId='01990000-7000-7000-8000-020000000008'
        geometry={{ "height": 44, "width": 120, "x": 40, "y": 120 }}
        label='Back'
        onClick={() => void run_0()}
      />
    </div>
  )
}
