/**
 * Generated by @mdt/generator — MDT page 'Home' (01990000-7000-7000-8000-010000000001).
 * Generator-owned: edits may be overwritten on regeneration
 * (see .mdt/generator-manifest.json).
 */
import NewResearchOverlay from './NewResearchOverlay'
import { MdtButton } from '../elements/MdtButton'
import { MdtChat } from '../elements/MdtChat'
import { MdtInput } from '../elements/MdtInput'
import { generatedVariables } from '../generated-variables'
import { mdtElementStyle } from '../elements/layout'
import { resolveSource } from '../bindings'
import { storeForScope } from '../variables'
import { useAgentRun } from '../agent-client'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function HomePage() {
  const navigate = useNavigate()
  const [values, setValues] = useState<Record<string, unknown>>({})
  const [agentOutputs, setAgentOutputs] = useState<Record<string, string>>({})
  const [capabilityOutputs, setCapabilityOutputs] = useState<Record<string, unknown>>({})
  const [openOverlays, setOpenOverlays] = useState<string[]>([])
  const agent_0 = useAgentRun('01990000-7000-7000-8000-030000000001')
  const setValue = (elementId: string, value: unknown): void => {
    setValues((previous) => ({ ...previous, [elementId]: value }))
  }
  const closeOverlay = (pageId: string): void => {
    setOpenOverlays((previous) => previous.filter((id) => id !== pageId))
  }
  const bindingCtx = { values, variables: generatedVariables, agentOutputs, capabilityOutputs }
  useEffect(() => {
    setAgentOutputs((previous) => ({ ...previous, '01990000-7000-7000-8000-030000000001': agent_0.lastResponse }))
  }, [agent_0.lastResponse])
  // data binding 01990000-7000-7000-8000-070000000001: variable → element 01990000-7000-7000-8000-020000000002 (value)
  const bound_0 = resolveSource({ "type": "variable", "variableId": "01990000-7000-7000-8000-060000000001" }, bindingCtx)
  async function run_0(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000001 (click)
    agent_0.send(toDisplayText(resolveSource({ "elementId": "01990000-7000-7000-8000-020000000002", "type": "elementValue" }, bindingCtx)))
  }
  async function run_1(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000002 (click)
    setOpenOverlays((previous) => (previous.includes('01990000-7000-7000-8000-010000000004') ? previous : [...previous, '01990000-7000-7000-8000-010000000004']))
  }
  async function run_2(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000007 (change)
    storeForScope('session').set('01990000-7000-7000-8000-060000000001', resolveSource({ "elementId": "01990000-7000-7000-8000-020000000002", "type": "elementValue" }, bindingCtx))
  }
  function toDisplayText(value: unknown): string {
    if (value === null || value === undefined) return ''
    if (typeof value === 'string') return value
    return JSON.stringify(value, null, 2)
  }
  return (
    <div className="mdt-page" data-mdt-page='Home' data-mdt-id='01990000-7000-7000-8000-010000000001' style={{ width: 1440, height: 1024 }}>
      {/* page background */}
      <style>{`.mdt-page[data-mdt-id='01990000-7000-7000-8000-010000000001'], .mdt-overlay[data-mdt-id='01990000-7000-7000-8000-010000000001'] { background: #ffffff; } `}</style>
      <div
        data-mdt-id='01990000-7000-7000-8000-020000000001'
        style={mdtElementStyle({ "height": 60, "width": 640, "x": 40, "y": 24 }, { "font-size": 32 })}
      >
        {'Research Assistant'}
      </div>
      <MdtInput
        mdtId='01990000-7000-7000-8000-020000000002'
        geometry={{ "height": 44, "width": 320, "x": 40, "y": 40 }}
        value={String(values['01990000-7000-7000-8000-020000000002'] ?? "")}
        placeholder='Ask anything'
        label='Query'
        onChange={(value) => {
          setValue('01990000-7000-7000-8000-020000000002', value)
          void run_2()
        }}
      />
      <MdtButton
        mdtId='01990000-7000-7000-8000-020000000003'
        geometry={{ "height": 44, "width": 120, "x": 400, "y": 40 }}
        label='Search'
        onClick={() => void run_0()}
      />
      <MdtButton
        mdtId='01990000-7000-7000-8000-020000000004'
        geometry={{ "height": 44, "width": 140, "x": 540, "y": 40 }}
        label='New research…'
        onClick={() => void run_1()}
      />
      <MdtChat
        mdtId='01990000-7000-7000-8000-020000000005'
        geometry={{ "height": 520, "width": 640, "x": 40, "y": 120 }}
        messages={agent_0.messages}
        running={agent_0.running}
        onSend={agent_0.send}
        onCancel={agent_0.cancel}
        label='Research chat'
        placeholder='Message the research agent…'
      />
      <NewResearchOverlay
        open={openOverlays.includes('01990000-7000-7000-8000-010000000004')}
        onClose={() => closeOverlay('01990000-7000-7000-8000-010000000004')}
      />
    </div>
  )
}
