/**
 * Generated by @mdt/generator — MDT modal page 'New Research' (01990000-7000-7000-8000-010000000004).
 * Generator-owned: edits may be overwritten on regeneration
 * (see .mdt/generator-manifest.json).
 */
import { MdtButton } from '../elements/MdtButton'
import { MdtInput } from '../elements/MdtInput'
import { generatedVariables } from '../generated-variables'
import { resolveSource } from '../bindings'
import { storeForScope } from '../variables'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function NewResearchOverlay({ open, onClose }: { open: boolean; onClose: () => void }) {
  const navigate = useNavigate()
  const [values, setValues] = useState<Record<string, unknown>>({})
  const [agentOutputs, setAgentOutputs] = useState<Record<string, string>>({})
  const [capabilityOutputs, setCapabilityOutputs] = useState<Record<string, unknown>>({})
  const setValue = (elementId: string, value: unknown): void => {
    setValues((previous) => ({ ...previous, [elementId]: value }))
  }
  const bindingCtx = { values, variables: generatedVariables, agentOutputs, capabilityOutputs }
  async function run_0(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000004 (click)
    onClose()
  }
  if (!open) return null
  return (
    <div className="mdt-overlay-backdrop" data-overlay-kind="modal" data-mdt-id='01990000-7000-7000-8000-010000000004' onClick={() => onClose()}>
      <div className="mdt-overlay" data-overlay-kind="modal" role="dialog" aria-modal="true" aria-label='New Research' style={{ width: 640, height: 320 }} onClick={(event) => event.stopPropagation()}>
      <MdtInput
        mdtId='01990000-7000-7000-8000-020000000009'
        geometry={{ "height": 44, "width": 320, "x": 40, "y": 40 }}
        value={String(values['01990000-7000-7000-8000-020000000009'] ?? "")}
        placeholder='Research topic…'
        label='Topic'
        onChange={(value) => setValue('01990000-7000-7000-8000-020000000009', value)}
      />
      <MdtButton
        mdtId='01990000-7000-7000-8000-02000000000a'
        geometry={{ "height": 44, "width": 120, "x": 480, "y": 240 }}
        label='Start'
        onClick={() => void run_0()}
      />
      </div>
    </div>
  )
}
