/**
 * Generated by @mdt/generator — MDT page 'Research' (01990000-7000-7000-8000-010000000002).
 * Generator-owned: edits may be overwritten on regeneration
 * (see .mdt/generator-manifest.json).
 */
import { MdtButton } from '../elements/MdtButton'
import { MdtCodeBlock } from '../elements/MdtCodeBlock'
import { MdtList } from '../elements/MdtList'
import { generatedVariables } from '../generated-variables'
import { resolveSource } from '../bindings'
import { storeForScope } from '../variables'
import { toArray } from '../bindings'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

export default function ResearchPage() {
  const navigate = useNavigate()
  const [values, setValues] = useState<Record<string, unknown>>({})
  const [agentOutputs, setAgentOutputs] = useState<Record<string, string>>({})
  const [capabilityOutputs, setCapabilityOutputs] = useState<Record<string, unknown>>({})
  const setValue = (elementId: string, value: unknown): void => {
    setValues((previous) => ({ ...previous, [elementId]: value }))
  }
  const bindingCtx = { values, variables: generatedVariables, agentOutputs, capabilityOutputs }
  // data binding 01990000-7000-7000-8000-070000000002: agentOutput → element 01990000-7000-7000-8000-02000000000c (text)
  const bound_0 = resolveSource({ "agentId": "01990000-7000-7000-8000-030000000001", "type": "agentOutput" }, bindingCtx)
  async function run_0(): Promise<void> {
    // interaction 01990000-7000-7000-8000-050000000005 (click)
    navigate('/details')
  }
  useEffect(() => {
    // bindOutput 01990000-7000-7000-8000-050000000006 → element 01990000-7000-7000-8000-020000000006 (items)
    setValue('01990000-7000-7000-8000-020000000006', capabilityOutputs['01990000-7000-7000-8000-040000000001'] ?? null)
  }, [capabilityOutputs])
  function toDisplayText(value: unknown): string {
    if (value === null || value === undefined) return ''
    if (typeof value === 'string') return value
    return JSON.stringify(value, null, 2)
  }
  return (
    <div className="mdt-page" data-mdt-page='Research' data-mdt-id='01990000-7000-7000-8000-010000000002' style={{ width: 1440, height: 1024 }}>
      <MdtList
        mdtId='01990000-7000-7000-8000-020000000006'
        geometry={{ "height": 420, "width": 640, "x": 40, "y": 120 }}
        items={[ "Run a search to populate results" ]}
        label='Results'
      />
      <MdtCodeBlock
        mdtId='01990000-7000-7000-8000-02000000000c'
        geometry={{ "height": 420, "width": 640, "x": 720, "y": 120 }}
        text={toDisplayText(bound_0)}
        label='Raw result'
      />
      <MdtButton
        mdtId='01990000-7000-7000-8000-02000000000b'
        geometry={{ "height": 44, "width": 160, "x": 40, "y": 40 }}
        label='View details'
        onClick={() => void run_0()}
      />
    </div>
  )
}
